import { SOP_FEE_LETTER_NOTICE, type SopSection } from "@/lib/sopAgenTypes";

/** SOP/AGEN/001 v01, sections 1 to 4 (wording kept as in the signed document). */
export const SOP_SECTIONS_A: readonly SopSection[] = [
  {
    id: "tentang-program",
    num: 1,
    title: "Tentang Program Agen Musafar",
    blocks: [
      { t: "p", text: "Program Agen Musafar merupakan program kemitraan bagi individu yang ingin membantu memasarkan dan menjual paket perjalanan Musafar kepada calon jamaah." },
      { t: "p", text: "Agen mendapatkan kesempatan memperoleh **komisi dari setiap jamaah yang berhasil didaftarkan melalui agen dan memenuhi seluruh ketentuan komisi yang berlaku.**" },
      { t: "p", text: "Agen tidak perlu mengurus operasional perjalanan jamaah. Proses administrasi, pembayaran, dokumen, visa, tiket, akomodasi, dan operasional perjalanan ditangani oleh tim Musafar sesuai dengan prosedur perusahaan." },
    ],
  },
  {
    id: "siapa-bisa-jadi-agen",
    num: 2,
    title: "Siapa yang Bisa Menjadi Agen?",
    blocks: [
      { t: "p", text: "Program Agen Musafar terbuka bagi:" },
      {
        t: "ul",
        items: [
          "Minimal berumur 17 Tahun.",
          "Karyawan.",
          "Pengusaha.",
          "Freelancer.",
          "Content creator.",
          "Influencer.",
          "Komunitas.",
          "Pemilik bisnis.",
          "Ibu rumah tangga.",
          "Mahasiswa.",
          "Profesional.",
          "Individu yang memiliki jaringan atau komunitas.",
          "Siapa pun yang memiliki kemampuan dan kemauan untuk memasarkan paket Musafar.",
          "Bukan dalam kerjasama dengan travel lain.",
        ],
      },
      { t: "p", text: "Tidak harus memiliki pengalaman di bidang travel." },
    ],
  },
  {
    id: "syarat-menjadi-agen",
    num: 3,
    title: "Syarat Menjadi Agen",
    blocks: [
      { t: "p", text: "Calon agen wajib memenuhi persyaratan berikut:" },
      { t: "h", text: "Persyaratan Umum" },
      {
        t: "ol",
        items: [
          "Warga Negara Indonesia.",
          "Mengirimkan identitas yang valid.",
          "Memiliki nomor WhatsApp aktif.",
          "Memiliki rekening bank aktif.",
          "Bersedia mengikuti ketentuan Program Agen Musafar.",
          "Bersedia menjaga nama baik Musafar.",
          "Bersedia mengikuti onboarding/training agen.",
          "Memahami bahwa agen merupakan partner pemasaran dan **bukan karyawan Musafar**, kecuali memiliki hubungan kerja terpisah dengan perusahaan.",
        ],
      },
      { t: "h", text: "Dokumen yang Diperlukan" },
      {
        t: "ol",
        items: [
          "Nama lengkap.",
          "Nomor KTP/identitas sesuai kebutuhan perusahaan.",
          "Nomor WhatsApp.",
          "Alamat/domisili.",
          "Nomor rekening.",
          "Nama pemilik rekening.",
          "Data tambahan lain yang diperlukan perusahaan.",
        ],
      },
    ],
  },
  {
    id: "rules-duta-musafar",
    num: 4,
    title: "Rules Duta Musafar",
    blocks: [
      { t: "h", id: "jenjang-keagenan", text: "a. Jenjang Keagenan" },
      {
        t: "table",
        head: ["Level", "Syarat", "Keuntungan"],
        rows: [
          ["Duta Musafar", "Registrasi Rp1.500.000", "Welcome Kit, Perlengkapan, komisi, pelatihan"],
          ["Duta Musafar Silver", "Minimal 1-15 jamaah/tahun", "Bonus dan Komisi"],
          ["Duta Musafar Gold", "Minimal 15-30 jamaah/tahun", "Bonus dan Komisi lebih besar"],
          ["Duta Musafar Platinum", "Minimal 30 jamaah/tahun", "Komisi tertinggi + insentif khusus"],
        ],
      },
      { t: "h", id: "pendaftaran-agen", text: "b. Pendaftaran Agen" },
      { t: "p", text: "Biaya registrasi: Rp1.500.000 (sekali seumur hidup)" },
      { t: "p", text: "**Mendapatkan:**" },
      { t: "p", text: "Welcome kit :" },
      { t: "ul", items: ["Rompi Exclusive", "Tumbler Exclusive", "Id card agen", "Buku panduan agen"] },
      { t: "p", text: "Perlengkapan :" },
      { t: "ul", items: ["Koper", "Ihram", "Mukena", "Koko", "abaya", "Tumbler"] },
      { t: "p", text: "Marketing kit :" },
      {
        t: "ul",
        items: [
          "Formulir Pendaftaran Jamaah",
          "Materi promosi: Banner.",
          "Materi promosi digital: Flyer, Katalog, dan Itinerary, video konten, photo konten.",
          "Grup WhatsApp khusus Agen",
          "Pelatihan penjualan gratis",
        ],
      },
      { t: "p", text: "**Pembayaran Pendaftaran Agen:**" },
      { t: "p", text: "Pembayaran dapat dibayarkan ke Rekening" },
      { t: "ul", items: ["BCA a.n Musa Amanah Wisata PT 1643337111", "BSI a.n Musa Amanah Wisata PT 7213170788", "BNI a.n Musa Amanah Wisata PT 1784469461"] },
      { t: "p", text: "Setelah melakukan pembayaran, kirimkan bukti transfer ke PIC yang bersangkutan" },
      { t: "h", id: "hak-agen-4c", text: "c. Hak Agen" },
      {
        t: "ul",
        items: [
          "Menjual seluruh produk Musafar.",
          "Mendapat komisi setiap jamaah.",
          "Mengikuti pelatihan gratis.",
          "Mendapat materi promosi.",
          "Mengikuti gathering agen.",
          "Mendapat sertifikat Agen Resmi.",
        ],
      },
      { t: "h", id: "kewajiban-agen-4d", text: "d. Kewajiban Agen" },
      {
        t: "ul",
        items: [
          "Menjaga nama baik Musafar.",
          "Tidak memberikan informasi palsu.",
          "Tidak mengubah harga paket kecuali kesepakatan B2B.",
          "Tidak menerima uang jamaah ke rekening pribadi tanpa izin perusahaan.",
          "Mengikuti SOP Musafar.",
          "Aktif mengikuti pembinaan.",
        ],
      },
      { t: "h", id: "skema-komisi-4e", text: "e. Skema Komisi" },
      { t: "notice", text: SOP_FEE_LETTER_NOTICE },
      { t: "p", text: "**Umrah Reguler (Silver)**" },
      { t: "p", text: "Komisi per Jamaah: Rp1.000.000 - 1.500.000" },
      { t: "p", text: "**Umroh Reguler (Gold)**" },
      { t: "p", text: "Komisi per Jamaah: Rp1.500.000 - 2.500.000" },
      { t: "p", text: "**Umroh Reguler (Platinum)**" },
      { t: "p", text: "Komisi per Jamaah: Rp2.000.000 - 3.000.000" },
      { t: "p", text: "**Haji Khusus**" },
      { t: "p", text: "Komisi: Rp5.000.000" },
      { t: "h", id: "bonus-closing-silver", text: "Bonus Closing Silver" },
      { t: "p", text: "5 Jamaah = Bonus Rp500.000" },
      { t: "p", text: "10 Jamaah = Bonus Rp1.500.000" },
      { t: "p", text: "40 Jamaah = Motor Listrik atau Cash" },
      { t: "h", id: "reward-tahunan", text: "Reward Tahunan" },
      { t: "p", text: "**Top 10 Agen**" },
      { t: "ul", items: ["Piagam", "Trophy", "Uang Tunai"] },
      { t: "p", text: "**Top 3 Agen**" },
      { t: "ul", items: ["Piagam", "Trophy", "Uang tunai"] },
      { t: "p", text: "**Grand Prize**" },
      { t: "ul", items: ["Piagam", "Trophy", "Motor (sesuai target 50pax)"] },
      { t: "p", text: "**Best Rookie**" },
      { t: "ul", items: ["Trophy", "Uang tunai"] },
      { t: "h", id: "program-bulanan", text: "Program Bulanan" },
      {
        t: "ul",
        items: [
          "Workshop Digital Marketing",
          "Training Online",
          "Sharing Closing",
          "Kajian Umrah",
          "Update Produk",
          "Bedah Handling Objection",
          "Agen freelance aktif dapat bonus tambahan setiap bulan",
        ],
      },
      { t: "h", id: "program-referral", text: "Program Referral" },
      { t: "p", text: "**Agen mengajak agen baru.**" },
      { t: "p", text: "**Reward:**" },
      { t: "ul", items: ["Bonus tambahan 30% jika agen baru tersebut berhasil memberangkatkan jamaah."] },
      { t: "h", id: "marketing-support", text: "Marketing Support" },
      { t: "p", text: "**Musafar menyediakan:**" },
      { t: "ul", items: ["Brosur", "Flyer", "Banner", "Poster", "Video Promosi", "Template Story", "Feed Instagram", "Katalog Paket", "Pricelist"] },
      { t: "h", id: "target-agen", text: "Target Agen" },
      { t: "p", text: "**Minimal setiap agen:**" },
      { t: "ul", items: ["1 jamaah setiap 1 bulan", "atau 12 jamaah/tahun"] },
      { t: "h", id: "masa-keaktifan", text: "Masa Keaktifan" },
      { t: "p", text: "**Agen tetap aktif apabila:**" },
      {
        t: "ul",
        items: [
          "Mengikuti pembinaan minimal 6 kali/tahun.",
          "Tidak melanggar SOP.",
          "Tidak melakukan penipuan atau tindakan yang merugikan perusahaan.",
        ],
      },
      { t: "h", id: "program-komunitas", text: "Program Komunitas \"Duta Musafar\"" },
      { t: "p", text: "**Seluruh agen tergabung dalam komunitas resmi yang mendapatkan:**" },
      {
        t: "ul",
        items: [
          "Update promo tercepat",
          "Informasi seat pesawat",
          "Jadwal keberangkatan",
          "Training eksklusif",
          "Sharing keberhasilan agen",
          "Gathering tahunan",
          "Kajian rutin",
          "Kompetisi penjualan",
        ],
      },
      { t: "h", id: "road-to-baitullah", text: "Program \"Road to Baitullah\"" },
      { t: "p", text: "**Program kompetisi selama 1 tahun.**" },
      { t: "p", text: "**Target penjualan akan dikonversi menjadi poin.**" },
      { t: "p", text: "**Contoh:**" },
      {
        t: "table",
        head: ["Aktivitas", "Poin"],
        rows: [
          ["1 Jamaah Umrah", "100"],
          ["1 Jamaah Haji", "300"],
          ["Mengikuti Training", "20"],
          ["Mengadakan Gathering", "30"],
        ],
      },
      { t: "p", text: "**Poin dapat ditukar dengan:**" },
      { t: "ul", items: ["Merchandise", "Voucher Belanja", "Cashback Umrah", "Tiket Wisata", "Umrah Gratis"] },
      { t: "p", text: "Sesuai dengan kebijakan reward tahunan" },
      { t: "h", id: "step-1", text: "STEP 1 — Isi Formulir Pendaftaran" },
      { t: "p", text: "Calon agen mengisi formulir resmi Program Agen Musafar." },
      { t: "h", id: "step-2", text: "STEP 2 — Verifikasi Data" },
      { t: "p", text: "Tim Musafar melakukan verifikasi data calon agen." },
      { t: "h", id: "step-3", text: "STEP 3 — Persetujuan" },
      { t: "p", text: "Calon agen yang memenuhi persyaratan akan mendapatkan persetujuan sebagai agen." },
      { t: "h", id: "step-4", text: "STEP 4 — Mendapatkan AGENT ID" },
      { t: "p", text: "Setiap agen mendapatkan **Agent ID unik**." },
      { t: "p", text: "Agent ID digunakan untuk:" },
      {
        t: "ul",
        items: ["Registrasi lead.", "Identifikasi transaksi.", "Pencatatan penjualan.", "Perhitungan komisi.", "Pelaporan kinerja agen."],
      },
      { t: "h", id: "step-5", text: "STEP 5 — Onboarding Agen" },
      { t: "p", text: "Agen mendapatkan informasi mengenai:" },
      {
        t: "ul",
        items: [
          "Produk Musafar.",
          "Pricelist.",
          "Materi promosi. (dikirimkan oleh PIC Musafar)",
          "Cara mendapatkan lead.",
          "Cara registrasi lead.",
          "Cara follow-up.",
          "Cara melakukan closing.",
          "Prosedur pendaftaran jamaah.",
          "Ketentuan komisi.",
          "Etika agen.",
        ],
      },
      { t: "p", text: "Setelah seluruh proses selesai, agen dinyatakan **AKTIF**." },
    ],
  },
];
