import type { SopSection } from "@/lib/sopAgenTypes";

/** SOP/AGEN/001 v01, sections 5 to 8 (wording kept as in the signed document). */
export const SOP_SECTIONS_B: readonly SopSection[] = [
  {
    id: "status-agen",
    num: 5,
    title: "Status Agen",
    blocks: [
      { t: "h", text: "A. CALON AGEN" },
      { t: "p", text: "Status sebelum proses verifikasi selesai." },
      { t: "p", text: "Belum diperbolehkan melakukan transaksi atas nama Musafar." },
      { t: "h", text: "B. AGEN AKTIF" },
      { t: "p", text: "Agen yang:" },
      { t: "ul", items: ["Telah diverifikasi.", "Telah memiliki Agent ID.", "Telah mengikuti onboarding.", "Menyetujui ketentuan Program Agen Musafar."] },
      { t: "p", text: "Agen aktif berhak memasarkan produk dan memperoleh komisi sesuai ketentuan." },
      { t: "h", text: "C. AGEN NONAKTIF" },
      { t: "p", text: "Agen dapat dinyatakan nonaktif apabila tidak melakukan aktivitas dalam periode yang ditentukan perusahaan (3 bulan) atau tidak memenuhi ketentuan administrasi." },
      { t: "h", text: "D. AGEN DIBERHENTIKAN" },
      { t: "p", text: "Keagenan dapat dihentikan apabila agen melakukan pelanggaran berat atau tindakan yang merugikan jamaah/perusahaan." },
    ],
  },
  {
    id: "apa-yang-dilakukan-agen",
    num: 6,
    title: "Apa yang Dilakukan Agen?",
    blocks: [
      { t: "p", text: "Tugas utama agen adalah:" },
      { t: "h", id: "mencari-calon-jamaah", text: "1. Mencari Calon Jamaah" },
      { t: "p", text: "Agen dapat menawarkan paket Musafar kepada:" },
      {
        t: "ul",
        items: [
          "Keluarga.",
          "Teman.",
          "Tetangga.",
          "Komunitas.",
          "Relasi kerja.",
          "Followers.",
          "Database pribadi yang diperoleh secara sah.",
          "Memastikan tanggal yang ditawarkan seatnya masih tersedia",
        ],
      },
      { t: "h", id: "mengenalkan-produk", text: "2. Mengenalkan Produk" },
      { t: "p", text: "Agen menjelaskan:" },
      {
        t: "ul",
        items: ["Paket perjalanan.", "Harga.", "Jadwal keberangkatan.", "Fasilitas.", "Ketentuan pembayaran.", "Informasi lain sesuai materi resmi Musafar."],
      },
      { t: "h", id: "melakukan-follow-up", text: "3. Melakukan Follow-up" },
      { t: "p", text: "Agen melakukan komunikasi dan follow-up terhadap calon jamaah sampai calon jamaah mengambil keputusan." },
      { t: "h", id: "membantu-pendaftaran", text: "4. Membantu pendaftaran calon jamaah" },
      { t: "p", text: "Apabila calon jamaah siap melakukan pendaftaran, agen membantu calon jamaah memenuhi persyaratan daftar, antara lain:" },
      { t: "p", text: "Persyaratan Umroh Musafar :" },
      {
        t: "ol",
        items: [
          "DP sebesar 5 juta/perorang ( pelunasan maksimal sebulan sebelum keberangkatan)",
          "Soft File KTP",
          "Soft file KK",
          "Vaksin Meningitis dan Polio",
          "Soft File Buku Nikah (bagi yg sudah menikah)",
          "Paspor asli",
          "Soft File akta anak jika bersama anak",
          "Soft file Foto Diri",
          "Mengisi Formulir Pendaftaran",
        ],
      },
      { t: "p", text: "Seluruh persyaratan dikirimkan ke PIC Musafar." },
      { t: "h", id: "materi-promosi", text: "5. Penggunaan dan penyebaran Materi Promosi" },
      { t: "p", text: "**a. Penggunaan Identitas Musafar pada Media Sosial**" },
      {
        t: "ul",
        items: [
          "**Agen Resmi Berkantor** diperbolehkan memiliki dan mengelola akun media sosial yang menggunakan nama, identitas, atau branding **Musafar**, dengan tetap mengikuti ketentuan branding dan arahan dari Manajemen Musafar.",
          "**Agen Individu** tidak diperbolehkan membuat atau mengelola akun media sosial yang menggunakan nama, identitas, atau branding **Musafar** seolah-olah merupakan akun resmi/cabang Musafar.",
        ],
      },
      { t: "p", text: "**b. Penggunaan Materi Promosi Musafar**" },
      {
        t: "ul",
        items: [
          "Seluruh **materi promosi resmi** yang disediakan oleh Musafar, seperti flyer, poster, video, foto, katalog, dan materi digital lainnya, diperbolehkan untuk digunakan oleh agen pada seluruh media sosial pribadi agen.",
          "Agen wajib menggunakan materi promosi tersebut **sesuai dengan materi asli** dan tidak diperkenankan mengubah informasi penting seperti harga, fasilitas, jadwal keberangkatan, program, maupun ketentuan lainnya tanpa persetujuan Manajemen Musafar.",
        ],
      },
      { t: "p", text: "**c. Pembuatan Konten Promosi oleh Agen**" },
      {
        t: "ul",
        items: [
          "Agen diperbolehkan membuat konten promosi secara mandiri untuk mendukung pemasaran produk Musafar.",
          "Setiap konten yang dibuat sendiri oleh agen **wajib melalui proses verifikasi dan mendapatkan persetujuan dari Manajemen Musafar sebelum dipublikasikan**.",
          "Konten yang telah disetujui wajib dipublikasikan sesuai dengan informasi dan ketentuan yang telah diberikan oleh Manajemen Musafar.",
        ],
      },
      { t: "p", text: "**d. Ketentuan Syariat dalam Pembuatan Konten**" },
      { t: "p", text: "Setiap konten promosi yang dibuat oleh agen wajib memperhatikan dan menjaga ketentuan syariat Islam, antara lain:" },
      {
        t: "ul",
        items: [
          "Tidak menampilkan **aurat**, baik laki-laki maupun perempuan.",
          "Tidak menggunakan **musik atau nada yang berasal dari alat musik** sebagai bagian dari konten.",
          "Tidak menampilkan **kedekatan atau interaksi yang tidak sesuai syariat antara laki-laki dan perempuan yang bukan mahram**.",
          "Tidak mengandung unsur, gambar, bahasa, atau penyampaian yang bertentangan dengan nilai-nilai Islam.",
          "Menjaga adab, etika, dan citra baik Musafar dalam setiap materi yang dipublikasikan.",
        ],
      },
      { t: "p", text: "**e. Tanggung Jawab Agen**" },
      { t: "p", text: "Setiap agen bertanggung jawab atas materi yang dibuat dan dipublikasikan melalui media sosial pribadi. Agen wajib memastikan bahwa seluruh konten telah sesuai dengan **ketentuan branding Musafar, informasi produk, serta prinsip syariat** yang ditetapkan oleh Manajemen Musafar." },
      { t: "p", text: "Pelanggaran terhadap ketentuan penggunaan identitas, materi promosi, maupun standar konten dapat menjadi dasar bagi Manajemen Musafar untuk memberikan **teguran, meminta penghapusan konten, pembatasan penggunaan materi promosi, hingga evaluasi status keagenan** sesuai tingkat pelanggaran." },
      { t: "h", id: "hak-komisi-agen", text: "6. Ketentuan Hak Komisi Agen" },
      { t: "p", text: "Setiap calon jamaah yang berasal dari agen **WAJIB didaftarkan sebagai lead terlebih dahulu.**" },
      { t: "p", text: "Data minimal:" },
      { t: "ul", items: ["Nama calon jamaah.", "Nomor WhatsApp.", "Paket yang diminati.", "Agent ID.", "Tanggal registrasi"] },
      { t: "p", text: "**1. Kepemilikan Jamaah oleh Agen**" },
      { t: "p", text: "Calon jamaah menjadi tanggung jawab dan hak komisi agen apabila agen tersebut **meng-handle calon jamaah secara aktif sejak proses pendaftaran hingga pelunasan**." },
      { t: "p", text: "**2. Calon Jamaah yang Berasal dari Sosial Media atau Media Promosi**" },
      { t: "p", text: "Apabila calon jamaah memperoleh informasi dari **Status WhatsApp agen**, namun agen tersebut **tidak pernah melakukan komunikasi atau follow-up secara langsung**, baik melalui chat maupun tatap muka, kemudian calon jamaah menghubungi agen lain (**Agen 2**) dan Agen 2 yang melakukan proses konsultasi hingga closing, maka **100% hak komisi menjadi milik Agen 2**." },
      { t: "p", text: "**3. Pengalihan Bantuan dari Agen 1 kepada Agen 2**" },
      { t: "p", text: "Apabila calon jamaah telah di-handle oleh **Agen 1**, kemudian Agen 1 meminta bantuan **Agen 2** untuk memberikan penjelasan, melakukan follow-up, hingga membantu proses closing, maka pembagian komisi ditetapkan sebagai berikut:" },
      { t: "ul", items: ["**Agen 1: 30% dari total komisi**", "**Agen 2: 70% dari total komisi**"] },
      { t: "p", text: "Apabila calon jamaah sudah mendaftar umroh/haji melalui **Agen 1**, lalu **Agen 1** meminta bantuan **Agen 2** untuk transaksi selanjutnya, maka pembagian komisi ditetapkan sebagai berikut :" },
      { t: "ul", items: ["**Agen 1: 60% dari total komisi**", "**Agen 2: 40% dari total komisi**"] },
      { t: "p", text: "**4. Bukti dan Pencatatan Handling Jamaah**" },
      { t: "p", text: "Setiap agen wajib melakukan pencatatan calon jamaah yang sedang di-handle, termasuk **nama jamaah, tanggal mulai komunikasi, riwayat follow-up, dan status transaksi**, sebagai dasar penentuan hak komisi apabila terjadi klaim atau perselisihan antar agen." },
      { t: "p", text: "**5. Ketentuan Perselisihan**" },
      { t: "p", text: "Apabila terdapat perselisihan mengenai kepemilikan calon jamaah atau hak komisi, keputusan akan ditentukan berdasarkan **riwayat komunikasi, bukti follow-up, dan data yang tercatat pada sistem/database Musafar**. Keputusan manajemen bersifat final." },
      { t: "h", id: "lead-protection", text: "Lead Protection" },
      { t: "p", text: "Lead yang telah terdaftar mendapatkan perlindungan selama:" },
      { t: "p", text: "**30 HARI KALENDER**" },
      { t: "p", text: "sejak tanggal registrasi, dengan syarat agen melakukan follow-up secara aktif." },
      { t: "p", text: "**Lead dianggap aktif apabila:**" },
      {
        t: "ul",
        items: [
          "Agen melakukan follow-up.",
          "Calon jamaah masih memberikan respons.",
          "Terdapat proses konsultasi.",
          "Terdapat pembahasan mengenai paket.",
          "Terdapat indikasi calon jamaah masih berminat.",
        ],
      },
      { t: "p", text: "**Lead dapat dinyatakan tidak aktif apabila:**" },
      {
        t: "ul",
        items: ["Tidak ada follow-up.", "Calon jamaah tidak dapat dihubungi.", "Calon jamaah menyatakan tidak berminat.", "Masa perlindungan telah berakhir."],
      },
    ],
  },
  {
    id: "ketentuan-harga",
    num: 7,
    title: "Ketentuan Harga",
    blocks: [
      { t: "p", text: "Agen **WAJIB menggunakan harga resmi Musafar.**" },
      { t: "p", text: "Agen tidak diperbolehkan:" },
      {
        t: "ul",
        items: [
          "Mengubah harga.",
          "Memberikan diskon pribadi. (jika terdapat diskon maka akan dikurangi dari fee komisi)",
          "Menjanjikan cashback pribadi.",
          "Menambahkan fasilitas yang tidak tersedia.",
          "Mengubah itinerary.",
          "Membuat promo sendiri atas nama Musafar.",
        ],
      },
      { t: "p", text: "Apabila terdapat promo khusus, agen wajib menggunakan materi dan harga yang telah disetujui perusahaan." },
    ],
  },
  {
    id: "pembayaran-jamaah",
    num: 8,
    title: "Pembayaran Jamaah",
    blocks: [
      { t: "p", text: "Seluruh pembayaran jamaah wajib dilakukan melalui **rekening/metode pembayaran resmi Musafar.**" },
      { t: "p", text: "Agen tidak diperbolehkan menerima pembayaran jamaah ke rekening pribadi tanpa persetujuan perusahaan." },
      { t: "p", text: "Apabila agen menerima uang jamaah tanpa prosedur resmi, segala risiko dan konsekuensi menjadi tanggung jawab agen sesuai ketentuan perusahaan." },
    ],
  },
];
