import type { SopSection } from "@/lib/sopAgenTypes";

/** SOP/AGEN/001 v01, sections 18 to 25 (wording kept as in the signed document). */
export const SOP_SECTIONS_D: readonly SopSection[] = [
  {
    id: "larangan-agen",
    num: 18,
    title: "Larangan Agen",
    blocks: [
      { t: "p", text: "Agen DILARANG:" },
      {
        t: "ul",
        items: [
          "Mengaku sebagai karyawan Musafar apabila bukan karyawan.",
          "Menjanjikan keberangkatan/fasilitas di luar ketentuan.",
          "Mengubah harga tanpa persetujuan.",
          "Membuat promo pribadi.",
          "Menerima uang jamaah ke rekening pribadi tanpa izin.",
          "Mengambil lead agen lain.",
          "Memalsukan data.",
          "Membuat transaksi fiktif.",
          "Menyebarkan data jamaah.",
          "Menggunakan logo/nama Musafar untuk kepentingan yang tidak berkaitan dengan program agen.",
          "Melakukan tindakan yang merugikan jamaah atau Musafar.",
          "Menyerahkan tanggung jawab dalam menghandle Leads kepada orang lain.",
        ],
      },
    ],
  },
  {
    id: "penanganan-komplain",
    num: 19,
    title: "Penanganan Komplain Jamaah",
    blocks: [
      { t: "p", text: "Jika jamaah memiliki keluhan:" },
      { t: "flow", steps: ["JAMAAH", "AGEN", "PIC MUSAFAR", "DIVISI TERKAIT", "MANAGEMENT"] },
      { t: "p", text: "Agen wajib meneruskan komplain kepada PIC dan tidak diperkenankan memberikan keputusan yang berada di luar kewenangannya." },
      { t: "p", text: "Khusus keputusan mengenai:" },
      { t: "ul", items: ["Refund.", "Kompensasi.", "Perubahan fasilitas.", "Perubahan jadwal.", "Perubahan itinerary."] },
      { t: "p", text: "merupakan kewenangan Musafar." },
    ],
  },
  {
    id: "evaluasi-agen",
    num: 20,
    title: "Evaluasi Agen",
    blocks: [
      { t: "p", text: "Agen dapat dievaluasi berdasarkan:" },
      {
        t: "ul",
        items: [
          "Jumlah lead.",
          "Aktivitas follow-up.",
          "Jumlah closing.",
          "Jumlah jamaah.",
          "Omzet.",
          "Kepatuhan terhadap SOP.",
          "Kualitas pelayanan.",
          "Jumlah komplain.",
          "Keaktifan agen.",
        ],
      },
      { t: "p", text: "Agen yang tidak aktif dalam periode tertentu dapat diberikan status **NONAKTIF**." },
    ],
  },
  {
    id: "sanksi",
    num: 21,
    title: "Sanksi",
    blocks: [
      { t: "p", text: "Pelanggaran dapat dikenakan:" },
      { t: "h", text: "Level 1 — Teguran Lisan" },
      { t: "p", text: "Untuk pelanggaran ringan." },
      { t: "h", text: "Level 2 — Peringatan Tertulis" },
      { t: "p", text: "Untuk pelanggaran berulang." },
      { t: "h", text: "Level 3 — Pembekuan Agen" },
      { t: "p", text: "Agen sementara tidak dapat melakukan aktivitas tertentu." },
      { t: "h", text: "Level 4 — Pemutusan Keagenan" },
      { t: "p", text: "Untuk pelanggaran berat seperti:" },
      {
        t: "ul",
        items: [
          "Penipuan.",
          "Penyalahgunaan dana jamaah.",
          "Pemalsuan data.",
          "Manipulasi transaksi.",
          "Penyalahgunaan nama Musafar.",
          "Tindakan yang merugikan jamaah/ nama baik perusahaan.",
        ],
      },
    ],
  },
  {
    id: "alur-menjadi-agen",
    num: 22,
    title: "Alur Menjadi Agen Musafar",
    blocks: [
      {
        t: "flow",
        steps: [
          "DAFTAR",
          "VERIFIKASI DATA",
          "DISETUJUI",
          "DAPAT AGENT ID",
          "ONBOARDING",
          "AGEN AKTIF",
          "CARI LEAD",
          "REGISTRASI LEAD",
          "FOLLOW-UP",
          "CLOSING",
          "JAMAAH BAYAR",
          "TRANSAKSI DIVERIFIKASI",
          "KOMISI ELIGIBLE",
          "APPROVAL",
          "KOMISI DIBAYARKAN",
        ],
      },
    ],
  },
  {
    id: "contoh-simulasi",
    num: 23,
    title: "Contoh Simulasi",
    blocks: [
      { t: "h", id: "contoh-1", text: "Contoh 1 — Komisi Berhasil" },
      { t: "p", text: "Agen A membawa 1 jamaah." },
      { t: "p", text: "Harga paket: Rp30.000.000" },
      { t: "p", text: "Komisi: Rp1.000.000" },
      { t: "p", text: "Jamaah:" },
      {
        t: "check",
        done: true,
        items: ["Lead terdaftar", "Agent ID tercatat", "Membayar sesuai ketentuan", "Data lengkap", "Tidak refund", "Tidak ada pelanggaran"],
      },
      { t: "p", text: "**Komisi Agen = Rp1.000.000**" },
      { t: "h", id: "contoh-2", text: "Contoh 2 — Jamaah Baru Bayar DP" },
      { t: "p", text: "Jamaah membayar DP tetapi ketentuan perusahaan menyatakan komisi baru diberikan setelah jamaah berangkat." },
      { t: "p", text: "Status:" },
      { t: "p", text: "**KOMISI = PENDING**" },
      { t: "p", text: "Komisi baru menjadi **ELIGIBLE** setelah syarat pembayaran terpenuhi." },
      { t: "h", id: "contoh-3", text: "Contoh 3 — Jamaah Refund" },
      { t: "p", text: "Komisi seharusnya Rp1.000.000." },
      { t: "p", text: "Namun jamaah membatalkan keberangkatan dan mendapatkan refund." },
      { t: "p", text: "**Komisi = TIDAK DIBAYARKAN.**" },
      { t: "p", text: "Jika komisi sudah terlanjur dibayarkan, perusahaan dapat melakukan recovery sesuai ketentuan." },
    ],
  },
  {
    id: "pernyataan-agen",
    num: 24,
    title: "Pernyataan Agen",
    blocks: [
      { t: "p", text: "Dengan mendaftar sebagai Agen Musafar, agen menyatakan bahwa:" },
      {
        t: "p",
        text: "Saya telah membaca, memahami, dan menyetujui seluruh ketentuan Program Agen Musafar serta bersedia menjalankan aktivitas sebagai agen sesuai SOP, menjaga nama baik Musafar, memberikan informasi yang benar kepada calon jamaah, dan mengikuti seluruh ketentuan mengenai leads, transaksi, pembayaran, dan komisi.",
      },
      { t: "fields", labels: ["Nama Agen", "Agent ID", "No. WhatsApp", "Tanggal", "Tanda Tangan"] },
    ],
  },
  {
    id: "ketentuan-penutup",
    num: 25,
    title: "Ketentuan Penutup",
    blocks: [
      { t: "p", text: "SOP ini merupakan pedoman pelaksanaan Program Agen Musafar." },
      { t: "p", text: "Musafar berhak melakukan perubahan terhadap ketentuan program, termasuk::" },
      {
        t: "ul",
        items: [
          "Persyaratan agen.",
          "Masa perlindungan lead.",
          "Besaran komisi.",
          "Sistem bonus.",
          "Mekanisme pembayaran komisi.",
          "Produk yang dapat dikomisi.",
          "Ketentuan evaluasi.",
        ],
      },
      { t: "p", text: "Setiap perubahan akan diinformasikan melalui media komunikasi resmi Musafar." },
      { t: "p", text: "Hal-hal yang belum diatur dalam SOP ini akan ditentukan oleh management Musafar." },
      { t: "signatures" },
    ],
  },
];
