project_id = "gmcbpcazyeaulwlmgmot"

[functions.bootstrap-admin]
verify_jwt = false

[functions.migrate-package-slugs]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.get-hero-preload]
verify_jwt = false
