project_id = "lcpjuaxiwbdzdozitwzi"

[functions.bootstrap-admin]
verify_jwt = false

[functions.migrate-package-slugs]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.get-hero-preload]
verify_jwt = false

[functions.short-link-redirect]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.migrate-drive-images]
verify_jwt = false

[functions.get-marketing-pixels]
verify_jwt = false
